# Generated by Django 5.1.1 on 2024-10-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
