# Generated by Django 5.1.1 on 2024-10-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
