# Generated by Django 5.1.1 on 2024-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
